name: CI/CD Pipeline for Kubernetes CronJob

env:
  IMAGE_NAME: <your-dockerhub-username>/go-cronjob:latest
  K8S_NAMESPACE: default

on:
  push:
    branches:
      - <branch_name>

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy Kubernetes CronJob
      run: |
        kubectl apply -f chart/cronjob.yaml -n ${{ env.K8S_NAMESPACE }}
